project:
  type: website
  render:
    - lectures/simulation.qmd
    - lectures/wrightfisher.qmd
    - lectures/coalescent.qmd
    - lectures/forward-simulation.qmd
  pre-render:
    - scripts/prepare-data.sh
institute: NBIS
from: markdown+emoji
bibliography: assets/bibliography.bib
revealjs-plugins:
  - nbishome
format:
  nbis-course-revealjs:
    theme:
      - custom.scss
    toc: true
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: false
    footer: GARG
    smaller: true
    highlight-style: gruvbox
    nbistitlelogo: false
    header-logo-left: assets/nbislogo_green_txt.svg
    header-logo-right: assets/SciLifeLab_Logotype_Green_POS.png
    header-logo-left-height: 40px
    header-logo-right-height: 40px
    logo: ""
    fig-height: 12
    fig-width: 10
    fig-align: center
    text-align: center
    width: 1050
    height: 700
    margin: 0.05
    navigation-mode: linear
    nbishome:
      url: https://ebp-nor.github.io/GARG/index.html
      position:
        left: 130px
        bottom: 14px
    ultitle: true
filters:
  - nbis-course
  - reveal-logo
  - diagram
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
execute:
  echo: true
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true
  freeze: auto
extensions:
 path: nbis-course-quarto
diagram:
  cache: false
  engine:
    tikz:
      execpath: lualatex
      header-includes:
        - '\usepackage{adjustbox}'
        - '\usetikzlibrary{calc, matrix, trees, arrows, shapes}'
        - '\usepackage{pgfplots}'
        - '\usepackage{pgfplotstable}'
        - '\usepackage{etoolbox}'
        - '\usepackage{ifthen}'
        - '\usepackage{xargs}'
        - '\usepackage{bm}'
        - '\usepackage{xkeyval}'
        - '\usepackage{graphicx}'
