---
title: Course preparation
toc: false
date: last-modified
execute:
  cache: false
nocite: |
  @lewanski_EraARGIntroduction_2024,
  @wohns_UnifiedGenealogyModern_2022,
  @stankowski_GeneticBasisRecent_2024, @_WhatTreeSequence_2024_
---

{{< include _rinit.qmd >}}

## Preparation

In preparation for the workshop, please make sure to work through the
workbooks listed below. In addition, we recommend you go through the
suggested readings.

### Workbooks

The workbooks can be run either as a
[JupyterLite](https://jupyterlite.readthedocs.io/en/stable/) instance
or in [Google Colab](https://colab.research.google.com/). Keep in mind
that you need a Google account to run the Colab exercies. Run the
HOWTO first (it takes 5-10 minutes), preferably in both engines, to
make sure everything works as expected and you understand the format
of the workbooks.

::: {.callout-important}

The Google Drive link below is temporary and points directly to the
Notebook version on Google Drive. The link will download a copy of the
notebook. Navigate to <https://colab.research.google.com> and click
"Upload" to upload the downloaded notebook, edit and save in your own
Google Drive.

:::

```{r }
#| label: r-list-workbooks
#| echo: false
#| eval: true
#| results: asis
workbooks <- data.frame(
  Topic = c(
    "HOWTO - introduction to exercises and JupyterLite",
    "An introduction to Python"
  ),
  link_lab_jlite = c(
    "HOWTO.ipynb",
    "python_intro.ipynb"
  ),
  link_lab_colab = c(
    "HOWTO.ipynb",
    "python_intro.ipynb"
  ),
  link_lab_drive = c(
    "1-6e6klPF5pi9DNuco4-zougklOVEcTZ1",
    "1vO-8rRNTfF8Hcx0MdUyMBhUW4C1gU54D"
  )
)

workbooks_md <- workbooks %>%
  # create links
  dplyr::mutate(link_lab_jlite = ifelse(
    is.na(link_lab_jlite), NA,
    gsub(
      ",", "",
      gsub(
        "([^,]+)",
        paste0(
          " **[{{< fa brands firefox-browser >}}](",
          server, "\\1)**"
        ),
        link_lab_jlite
      )
    )
  )) %>%
  dplyr::mutate(link_lab_colab = ifelse(
    is.na(link_lab_colab), NA,
    gsub(
      ",", "",
      gsub(
        "([^,]+)",
        paste0(
          " **[{{< fa brands google >}}](",
          colabhost, "\\1)**"
        ),
        link_lab_colab
      )
    )
  )) %>%
  dplyr::mutate(link_lab_drive = ifelse(
    is.na(link_lab_drive), NA,
    gsub(
      ",", "",
      gsub(
        "([^,]+)",
        paste0(
          " **[{{< fa brands google-drive >}}](",
          drivehost, "\\1)**"
        ),
        link_lab_drive
      )
    )
  ))

cat(
  print(kable(workbooks_md,
    format = "pipe", escape = FALSE,
    row.names = FALSE,
    col.names = c("Topic", "JupyterLite", "Google Colab", "Google Drive")
  )),
  "\n\n: {.hover .condensed .responsive tbl-colwidths=\"[55, 15, 15, 15]\"}\n\n"
)
```

### Suggested readings

::: {#refs}
:::
